equivalents = {
    "aqua": "water",
    "aqua/water": "water",
    "glycerol": "glycerin",
    "tocopherol": "vitamin e",
    "tocopherol acetate": "vitamin e",
    "butyrospermum parkii": "shea butter",
    "butyrospermum parkii (shea butter)": "shea butter",
    "parfum": "fragrance",
    "perfume": "fragrance",
    "dimethicone": "silicone",
    "cyclopentasiloxane": "silicone",
    "Beta Hydroxy Acid": "Salicylic Acid",
    "BHA": "Salicylic Acid",
    "Beta Hydroxy Acid (BHA)": "Salicylic Acid",
    "Triclosan": "antiseptic",
    "B3/Niacinamide": "Niacinamide",
    "b3": "Niacinamide",
    "Vitamin B3": "Niacinamide",
    "Vitamin B3/Niacinamide": "Niacinamide",
    "Niacinamide (Vitamin B3)": "Niacinamide",
    "Nicotinamide": "Niacinamide",
    "Vitamin PP": "Niacinamide",
    "Zinc Gluconate":  "Zinc PCA", 
    "Retinal": "Retinol",
    "Retinoic Acid": "Retinol",
    "Retinyl Palmitate": "Retinol",
    "Retinyl Acetate": "Retinol",
    "Retinyl Propionate": "Retinol",
    "Melaleuca Alternifolia (Tea Tree) Leaf Oil": "Tea Tree Oil",
    "Tea Tree (Melaleuca Alternifolia) Oil": "Tea Tree Oil",
    "Tea Tree Leaf Oil": "Tea Tree Oil",
    "Melaleuca Alternifolia Oil": "Tea Tree Oil",
    "Melaleuca Alternifolia Leaf Extract": "Tea Tree Oil",
    "Melaleuca Alternifolia Water": "Tea Tree Oil",
    "Terpinen-4-ol": "Tea Tree Oil",
    "Rosmarinus Officinalis Leaf Extract": "Rosmarinus officinalis",
    "Rosemary Extract": "Rosmarinus officinalis",
    "Rosemary Leaf Oil": "Rosmarinus officinalis",
    "Rosemary Oil": "Rosmarinus officinalis",
    "Rosmarinic Acid ": "Rosmarinus officinalis",
    "Ursolic Acid": "Rosmarinus officinalis",
    "Oleanolic Acid": "Rosmarinus officinalis",
    "Linum Usitatissimum": "Linum Usitatissimum Seed Extract",
    "Linseed Extract ": "Linum Usitatissimum Seed Extract",
    "Linseed Oil": "Linum Usitatissimum Seed Extract",
    "Flaxseed Extract": "Linum Usitatissimum Seed Extract",
    "Flax Extract": "Linum Usitatissimum Seed Extract",
    "Galacturonic Acid": "Linum Usitatissimum Seed Extract",
    "Avena sativa": "Avena Sativa (Oat) Kernel Extract",
    "Avena Sativa Kernel Extract": "Avena Sativa (Oat) Kernel Extract",
    "Avena Sativa Meal Extract": "Avena Sativa (Oat) Kernel Extract",
    "Colloidal Oatmeal": "Avena Sativa (Oat) Kernel Extract",
    "Oat Beta-Glucan": "Avena Sativa (Oat) Kernel Extract",
    "β-Glucan": "Avena Sativa (Oat) Kernel Extract",
    "Vitis Vinifera (Grape) Seed Oil": "Vitis Vinifera (Grape) Seed Extract",
    "Grape Seed Oil": "Vitis Vinifera (Grape) Seed Extract",
    "Grape Seed Extract": "Vitis Vinifera (Grape) Seed Extract",
    "Vitis Vinifera Oil": "Vitis Vinifera (Grape) Seed Extract",
    "Vitis Vinifera Seed Oil": "Vitis Vinifera (Grape) Seed Extract",
    "Safflower Oil ": "Carthamus Tinctorius (Safflower) Seed Oil",
    "Safflower Seed Oil": "Carthamus Tinctorius (Safflower) Seed Oil",
    "Carthamus Oil": "Carthamus Tinctorius (Safflower) Seed Oil",
    "Safflower Extract": "Carthamus Tinctorius (Safflower) Seed Oil",
    "Carthamus Tinctorius Seed Oil": "Carthamus Tinctorius (Safflower) Seed Oil",
    "Helianthus Annuus Seed Oil (Sunflower Oil)": "Helianthus Annuus (Sunflower) Seed Oil",
    "Sunflower Oil": "Helianthus Annuus (Sunflower) Seed Oil",
    "Sunflower Seed Oil": "Helianthus Annuus (Sunflower) Seed Oil",
    "Sunflower Extract": "Helianthus Annuus (Sunflower) Seed Oil",
    "Helianthus Annuus Oil": "Helianthus Annuus (Sunflower) Seed Oil",
    "Helianthus Oil ": "Helianthus Annuus (Sunflower) Seed Oil",
    "Argania Spinosa Kernel Oil": "Argan Oil",
    "Cannabis Sativa Seed Oil": "Hemp Seed Oil",
    "Rosa Canina Fruit Oil": "Rosehip Oil",
    "Oenothera Biennis Oil": "Evening Primrose Oil",
    "Centella Asiatica": "Centella Asiatica Extract",
    "Sodium Hyaluronate": "Hyaluronic Acid",
    "Hydrolyzed Hyaluronic Acid": "Hyaluronic Acid",
    "Sodium Acetylated Hyaluronate": "Hyaluronic Acid",
    "Epigallocatechin Gallate": "Camellia Sinensis Leaf Extract",
    "Green Tea Extract": "Camellia Sinensis Leaf Extract",
    "Ascorbic Acid": "Vitamin C",
    "Sodium Ascorbyl Phosphate": "Vitamin C",
    "Magnesium Ascorbyl Phosphate": "Vitamin C",
    "Ascorbyl Glucoside": "Vitamin C",
    "Ascorbyl Palmitate": "Vitamin C",
    "Tetrahexyldecyl Ascorbate": "Vitamin C",
    "Psoralea Corylifolia Extract": "Bakuchiol",
    "Babchi Oil": "Bakuchiol",
    "Protocatechuic Acid": "pca",
    "Hibiscus Sabdariffa Extract": "pca",
    "Kaolin": "Kaolin clay",
    "Glycyrrhiza Inflata Root Extract ": "Licochalcone A",
    "Glycyrrhiza Inflata Extract": "Licochalcone A",
    "Brimonidine":"Brimonidine Tartrate",
    "Brimonidine Tartrate Gel":"Brimonidine Tartrate",
    "α2-Adrenergic Receptor Agonist":"Brimonidine Tartrate",
    "ceramide EOP": "ceramide",
    "ceramide 1": "ceramide",
    "ceramide 2": "ceramide",
    "ceramide 3": "ceramide",
    "ceramide 6-II": "ceramide",
    "ceramide AP": "ceramide",
    "ceramide NP": "ceramide",
    "ceramide NS": "ceramide",
    "ceramide NG": "ceramide",
    "Phytoceramide": "ceramide",
    "Ceramide Complex": "ceramide",
    "Hydroxypropyl Bispalmitamide MEA": "ceramide",
    "Sphingolipids": "ceramide",
    "Glycosphingolipids": "ceramide",
    "Vitamin K1": "Vitamin K",
    "Phytonadione": "Vitamin K",
    "Retinaldehit (Retinal)": "Retinaldehyde",
    "Retinal": "Retinaldehyde",
    "Silicon Dioxide": "Silica",
    "Seaweed Extract": "Algae Extract",
    "Ozonized Olive Oil": "Ozonated Olive Oil",
    "Aloe Barbadensis Leaf Juice": "aloe vera",
    "Aloe Vera Gel": "aloe vera",
    "Aloe Vera Extract": "aloe vera",
    "Aloe Vera Powder": "aloe vera",
    "Milk acid": "Lactic Acid",
    "Hydroxyethanoic Acid": "Lactic Acid",
    "Simmondsia Chinensis Seed Oil": "Jojoba Oil",
    "Simmondsia Chinensis Oil": "Jojoba Oil",
    "Simmondsia Chinensis": "Jojoba Oil",
}
